project_id = "wwaldqgsedruplukxqdf"

[functions.transcribe-audio]
verify_jwt = false

[functions.process-memory]
verify_jwt = false

[functions.vault-collab-merge]
verify_jwt = true

[functions.proactive-engine]
verify_jwt = false
