// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwaldqgsedruplukxqdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3YWxkcWdzZWRydXBsdWt4cWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTU1MzUsImV4cCI6MjA2OTk3MTUzNX0.0E4SCTmtaoFO6CaNIh4wLQJPyJWOsPCcSrfKzi8k-K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});